version: '3'

services:
  web:
    container_name: web_app_konsultasi
    image: node
    command: sh -c "npm install && npx prisma migrate dev --name init && npm run dev"
    env_file: ".env"
    restart: always
    environment:
      DATABASE_URL: "mysql://root:$MYSQL_ROOT_PASSWORD@db/$MYSQL_DATABASE"
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - .:/app:rw
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network_app_konsultasi

  db:
    image: mariadb:latest
    container_name: db_app_konsultasi
    command: --default-authentication-plugin=mysql_native_password
    env_file: ".env"
    restart: always
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    networks:
      - network_app_konsultasi
    volumes:
      - dbcont:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin_app_konsultasi
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    networks:
      - network_app_konsultasi
    depends_on:
      - db

networks:
  network_app_konsultasi:
    driver: bridge
    name: network_app_konsultasi

volumes:
  .:
    name: web_app_konsultasi_volume
  dbcont:
    name: db_app_konsultasi_volume